---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.8.0-debug
    args: ["--context=git://github.com/rossini-bruno/kaniko-demo",
            "--destination=us-central1-docker.pkg.dev/charged-chess-357014/docker-test/devops-toolkit:1.0.0",
            "--snapshotMode=redo","--single-snapshot"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /var/secrets/google
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/google/key.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: pubsub-key

